langauge: cpp
sudo: false
dist: trusty

env:
    global:
        - FC=gfortran-4.8

script:
  - ./configure && make

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
