langauge: cpp
compiler: gcc
sudo: required
dist: trusty

env:
    global:
        - FC=gfortran

install:
    - sudo apt-get update
    - sudo apt-get install libblas-dev liblapack-dev

script:
  - ./configure && make

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
